package rootstudio.development.tms.features.serviceManagement.deliveryServiceManagement.service;

import org.springframework.data.domain.Page;
import rootstudio.development.tms.features.serviceManagement.deliveryServiceManagement.domains.request.AllDeliveryServiceRequest;
import rootstudio.development.tms.features.serviceManagement.deliveryServiceManagement.domains.request.CreateDeliveryServiceRequest;
import rootstudio.development.tms.features.serviceManagement.deliveryServiceManagement.domains.request.UpdateDeliveryServiceRequest;
import rootstudio.development.tms.features.serviceManagement.deliveryServiceManagement.domains.response.AllDeliveryServiceResponse;
import rootstudio.development.tms.features.serviceManagement.deliveryServiceManagement.domains.response.CreateDeliveryServiceResponse;
import rootstudio.development.tms.features.serviceManagement.deliveryServiceManagement.domains.response.DeliveryServiceDetailsResponse;
import rootstudio.development.tms.features.serviceManagement.deliveryServiceManagement.domains.response.UpdateDeliveryServiceResponse;

public interface DeliveryManagementService {
    Page<AllDeliveryServiceResponse> getAllDeliveryService(AllDeliveryServiceRequest request);
    DeliveryServiceDetailsResponse getDeliveryServiceById(String id);
    CreateDeliveryServiceResponse createDeliveryService(CreateDeliveryServiceRequest request);
    UpdateDeliveryServiceResponse updateDeliveryService(String id, UpdateDeliveryServiceRequest request);
}
